using System.Text.Json.Serialization;
using Betalgo.Ranul.OpenAI.Contracts.Enums.Image;
using Betalgo.Ranul.OpenAI.Contracts.Enums.Model;
using Betalgo.Ranul.OpenAI.Contracts.Interfaces;

namespace Betalgo.Ranul.OpenAI.Contracts.Requests.Image;

/// <summary>
///     <see href="https://platform.openai.com/docs/api-reference/images/create">
///         OpenAI API documentation
///     </see>
///     <see href="https://github.com/betalgo/openai/blob/master/Docs/openapi-split/components/schemas/createimagerequest.yml">
///         Source Definition
///     </see>
/// </summary>
public class CreateImageRequest : IRequest, IHasModelImage, IHasImageSize, IHasImageBackground, IHasImageOutputFormat, IHasImageQuality
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="CreateImageRequest" /> class.
    /// </summary>
    public CreateImageRequest()
    {
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="CreateImageRequest" /> class.
    /// </summary>
    /// <param name="prompt">
    ///     A text description of the desired image(s). The maximum length is 32000 characters for <c>gpt-image-1</c>, 1000
    ///     characters for <c>dall-e-2</c> and 4000 characters for <c>dall-e-3</c>.
    /// </param>
    public CreateImageRequest(string prompt)
    {
        Prompt = prompt;
    }

    /// <summary>
    ///     A text description of the desired image(s). The maximum length is 32000 characters for <c>gpt-image-1</c>, 1000
    ///     characters for <c>dall-e-2</c> and 4000 characters for <c>dall-e-3</c>.
    /// </summary>
    [JsonPropertyName("prompt")]
    public string Prompt { get; set; } = null!;

    /// <summary>
    ///     The number of images to generate. Must be between 1 and 10. For <c>dall-e-3</c>, only <c>n=1</c> is supported.
    /// </summary>
    [JsonPropertyName("n")]
    public int? N { get; set; }

    /// <summary>
    ///     The format in which generated images with <c>dall-e-2</c> and <c>dall-e-3</c> are returned. Must be one of
    ///     <c>url</c> or <c>b64_json</c>. URLs are only valid for 60 minutes after the image has been generated. This
    ///     parameter isn't supported for <c>gpt-image-1</c> which will always return base64-encoded images.
    /// </summary>
    [JsonPropertyName("response_format")]
    public ImageResponseFormat? ResponseFormat { get; set; }

    /// <summary>
    ///     The compression level (0-100%) for the generated images. This parameter is only supported for <c>gpt-image-1</c>
    ///     with the <c>webp</c> or <c>jpeg</c> output formats, and defaults to 100.
    /// </summary>
    [JsonPropertyName("output_compression")]
    public int? OutputCompression { get; set; }

    /// <summary>
    ///     Control the content-moderation level for images generated by <c>gpt-image-1</c>. Must be either <c>low</c> for less
    ///     restrictive filtering or <c>auto</c> (default value).
    /// </summary>
    [JsonPropertyName("moderation")]
    public ImageModeration? Moderation { get; set; }

    /// <summary>
    ///     The style of the generated images. This parameter is only supported for <c>dall-e-3</c>. Must be one of
    ///     <c>vivid</c> or <c>natural</c>. Vivid causes the model to lean towards generating hyper-real and dramatic images.
    ///     Natural causes the model to produce more natural, less hyper-real looking images.
    /// </summary>
    [JsonPropertyName("style")]
    public ImageStyle? Style { get; set; }

    /// <summary>
    ///     A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
    ///     <see href="https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids">Learn more</see>.
    /// </summary>
    [JsonPropertyName("user")]
    public string? User { get; set; }

    /// <summary>
    ///     Allows to set transparency for the background of the generated image(s).
    ///     This parameter is only supported for <c>gpt-image-1</c>. Must be one of
    ///     <c>transparent</c>, <c>opaque</c> or <c>auto</c> (default value). When <c>auto</c> is used, the
    ///     model will automatically determine the best background for the image.
    ///     <para />
    ///     If <c>transparent</c>, the output format needs to support transparency, so it
    ///     should be set to either <c>png</c> (default value) or <c>webp</c>.
    /// </summary>
    [JsonPropertyName("background")]
    public ImageBackground? Background { get; set; }

    /// <summary>
    ///     The format in which the generated images are returned. This parameter is only supported for <c>gpt-image-1</c>.
    ///     Must be one of <c>png</c>, <c>jpeg</c>, or <c>webp</c>.
    /// </summary>
    [JsonPropertyName("output_format")]
    public ImageOutputFormat? OutputFormat { get; set; }

    /// <summary>
    ///     The quality of the image that will be generated.
    ///     <para />
    ///     - <c>auto</c> (default value) will automatically select the best quality for the given model.
    ///     - <c>high</c>, <c>medium</c> and <c>low</c> are supported for <c>gpt-image-1</c>.
    ///     - <c>hd</c> and <c>standard</c> are supported for <c>dall-e-3</c>.
    ///     - <c>standard</c> is the only option for <c>dall-e-2</c>.
    /// </summary>
    [JsonPropertyName("quality")]
    public ImageQuality? Quality { get; set; }

    /// <summary>
    ///     The size of the generated images. Must be one of <c>1024x1024</c>, <c>1536x1024</c> (landscape), <c>1024x1536</c>
    ///     (portrait), or <c>auto</c> (default value) for <c>gpt-image-1</c>, one of <c>256x256</c>, <c>512x512</c>, or
    ///     <c>1024x1024</c> for <c>dall-e-2</c>, and one of <c>1024x1024</c>, <c>1792x1024</c>, or <c>1024x1792</c> for
    ///     <c>dall-e-3</c>.
    /// </summary>
    [JsonPropertyName("size")]
    public ImageSize? Size { get; set; }

    /// <summary>
    ///     The model to use for image generation. One of <c>dall-e-2</c>, <c>dall-e-3</c>, <c>gpt-image-1</c> or
    ///     <c>gpt-image-1-mini</c>. Defaults to <c>dall-e-2</c> unless a parameter specific to <c>gpt-image-1</c> is used.
    /// </summary>
    [JsonPropertyName("model")]
    public ImageModel? Model { get; set; }
}