using System.Text.Json;
using System.Text.Json.Serialization;

namespace Betalgo.Ranul.OpenAI.Contracts.Enums.Image;

/// <summary>
///     <see href="https://platform.openai.com/docs/api-reference/images/create#images_create-moderation">
///         OpenAI API documentation
///     </see>
///     Control the content-moderation level for images generated by gpt-image-1. Must be either low for less restrictive
///     filtering or auto (default value).
/// </summary>
[JsonConverter(typeof(Converter))]
public readonly struct ImageModeration(string value) : IEquatable<ImageModeration>
{
    /// <summary>
    ///     Literal <c>low</c>.
    /// </summary>
    public static ImageModeration Low { get; } = new("low");

    /// <summary>
    ///     Literal <c>auto</c>.
    /// </summary>
    public static ImageModeration Auto { get; } = new("auto");

    public string Value { get; } = value;
    public override string ToString() => Value;
    public bool Equals(ImageModeration other) => string.Equals(Value, other.Value, StringComparison.OrdinalIgnoreCase);
    public override bool Equals(object? obj) => obj is ImageModeration other && Equals(other);
    public override int GetHashCode() => StringComparer.OrdinalIgnoreCase.GetHashCode(Value);
    public static bool operator ==(ImageModeration left, ImageModeration right) => left.Equals(right);
    public static bool operator !=(ImageModeration left, ImageModeration right) => !(left == right);
    public static implicit operator string(ImageModeration format) => format.Value;
    public static implicit operator ImageModeration(string value) => new(value);

    public sealed class Converter : JsonConverter<ImageModeration>
    {
        public override ImageModeration Read(ref Utf8JsonReader reader, Type t, JsonSerializerOptions o) => new(reader.GetString()!);
        public override void Write(Utf8JsonWriter writer, ImageModeration value, JsonSerializerOptions o) => writer.WriteStringValue(value.Value);
    }
}